default:
  logger:
    log_level: "INFO"
  service:
    host: "0.0.0.0"
    port: 8282
    cert_file: "ssl_certs/localhost.crt"
    cert_key: "ssl_certs/localhost.key"
  chat_engine:
    model_root: "models"
    concurrent_limit: 5
    turn_config:
      turn_provider: "turn_server"
      urls:
        - "turn:139.224.57.224:3478?transport=udp"
        - "turn:139.224.57.224:3478?transport=tcp"
      username: "admin"
      credential: "admin"
    handler_search_path:
      - "src/handlers"
    handler_configs:
      LamClient:
        module: client/h5_rendering_client/client_handler_lam
        asset_path: "lam_samples/barbara.zip"
        # max time a session will last for
        connection_ttl: 900
      SileroVad:
        module: vad/silerovad/vad_handler_silero
        speaking_threshold: 0.5
        start_delay: 2048
        end_delay: 5000
        buffer_look_back: 5000
        speech_padding: 512
      SenseVoice:
        enabled: True
        module: asr/sensevoice/asr_handler_sensevoice
        model_name: "iic/SenseVoiceSmall"
      CosyVoice:
        enabled: True
        module: tts/bailian_tts/tts_handler_cosyvoice_bailian
        voice: "longxiaocheng"
        model_name: "cosyvoice-v1"
        api_key: "sk-3d984d1b13ac415f812b5cc9140eeffc" # default=os.getenv("DASHSCOPE_API_KEY")
      LLMOpenAICompatible:
        enabled: True
        module: llm/openai_compatible/llm_handler_openai_compatible
        model_name: "qwen3-vl-plus" # 或者 qwen-vl-max，需与百炼账号可用模型一致
        enable_video_input: True # 开启视频输入，确保模型支持视觉
        history_length: 20
        # model_name: "gemini-2.0-flash"
        system_prompt: "请你扮演一个 AI 助手，用简短的两三句对话来回答用户的问题，并在对话内容中加入合适的标点符号，不需要讨论标点符号相关的内容"
        api_url: "https://dashscope.aliyuncs.com/compatible-mode/v1"
        # api_url: 'http://127.0.0.1:11434/v1' # ollama
        # api_url: 'https://generativelanguage.googleapis.com/v1beta/openai/'
        api_key: "sk-3d984d1b13ac415f812b5cc9140eeffc" # default=os.getenv("DSHSCOPE_API_KEY")
      # Dify:
      #   enabled: True
      #   module: llm/dify/llm_handler_dify
      #   api_key: app-J3LiQRqh4MrOOvS6vpyrgIOW
      #   api_url: 'http://localhost/v1'
      LAM_Driver:
        module: avatar/lam/avatar_handler_lam_audio2expression
